# Generated by Django 5.2 on 2026-03-05 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("blog", "0003_alter_comment_options_alter_post_options_post_likes_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="post",
            name="category",
            field=models.CharField(
                choices=[
                    ("life", "Life"),
                    ("study", "Study"),
                    ("travel", "Travel"),
                    ("food", "Food"),
                    ("mood", "Mood"),
                    ("tech", "Tech"),
                ],
                default="life",
                max_length=20,
            ),
        ),
    ]
